name: Ghep Anh Va Audio Thanh Video

on:
  workflow_dispatch:
    inputs:
      image_file:
        description: 'Ten file anh trong Repo (VD: image.jpg)'
        required: true
        default: 'Lyme-Town-Hall-Offices-cropped-1024.jpeg'
      audio_file:
        description: 'Ten file am thanh trong Repo (VD: audio.mp3)'
        required: true
        default: 'audio.mp3'

jobs:
  create-video:
    runs-on: ubuntu-latest
    steps:
      - name: Lay ma nguon Repo
        uses: actions/checkout@v4

      - name: Cai dat ffmpeg
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg

      - name: Ghep anh va audio thanh video MP4
        run: |
          ffmpeg -loop 1 -i "${{ github.event.inputs.image_file }}" -i "${{ github.event.inputs.audio_file }}" -c:v libx264 -tune stillimage -c:a aac -b:a 192k -pix_fmt yuv420p -shortest output_video.mp4 -y

      - name: Tai video thanh pham ve máy
        uses: actions/upload-artifact@v4
        with:
          name: video-thanh-pham
          path: output_video.mp4
